name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download sane-fmt
        run: |
          curl -L https://github.com/sane-fmt/sane-fmt/releases/download/0.15.2/sane-fmt-x86_64-unknown-linux-gnu > ./sane-fmt
          chmod +x ./sane-fmt
      - id: sane-fmt
        name: Run sane-fmt
        run: |
          echo GITHUB_OUTPUT=$GITHUB_OUTPUT
          echo
          echo CONTENT:
          cat $GITHUB_OUTPUT
          echo
          echo Run sane-fmt
          ./sane-fmt --log-format=github-actions
          echo
          echo CONTENT:
          cat $GITHUB_OUTPUT
      - name: Inspect
        run: |
          echo total ${{ steps.sane-fmt.outputs.total }}
          echo changed ${{ steps.sane-fmt.outputs.changed }}
          echo unchanged ${{ steps.sane-fmt.outputs.unchanged }}
      - name: More summary
        run: |
          echo Goodbye >> $GITHUB_STEP_SUMMARY
      # - id: sane-fmt
      #   uses: sane-fmt/action@0.15.2
